@host = localhost:3000
@path = /company/server

### Success
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "QUEUE12345"
} 


###
<!-- 
Test Scenario: Server Available

Expected Outcome:
console: '{ customer_id: 1234567890 }'
success response: status: 200
{
  "customer_id": 1234567890
}
-->

//-----------------------------------------------------------//

### Success 2nd Poll
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "QUEUE12345"
} 


###
<!-- 
Test Scenario: Server Available 2nd Poll

Expected Outcome:
console: '{ customer_id: 1234567891 }'
success response: status: 200
{
  "customer_id": 1234567891
}
-->

//-----------------------------------------------------------//


### Success - queue_id all number
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "1234567890"
} 


###
<!-- 
Test Scenario: Server Available Queue ID all number

Expected Outcome:
console: '{ customer_id: 1234567890 }'
success response: status: 200 
{
  "customer_id": 1234567890
}
-->

//-----------------------------------------------------------//


### Success - queue_id all character
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "QUEUEABCDE"
} 


###
<!-- 
Test Scenario: Server Available Queue ID all character

Expected Outcome:
console: '{ customer_id: 1234567890 }'
success response: status: 200
{
  "customer_id": 1234567890
}
-->

//-----------------------------------------------------------//

### Success - queue_id not case sensitive
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "quEuE12345"
} 


###
<!-- 
Test Scenario: Server Available Queue ID not case sensitive

Expected Outcome:
console: '{ customer_id: 1234567890 }'
success response: status: 200
{
  "customer_id": 1234567890
}
-->

//-----------------------------------------------------------//

### Error - queue_id non-existent
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "ahfiehdief"
} 


###
<!-- 
Test Scenario: Server Available Queue ID non-existent

Expected Outcome:
console: 'Queue ID non-existent'
success response: 
{
  "message": "Queue ID provided is non existent",
  "status": 404,
  "code": "UNKNOWN_QUEUE"
}
-->

//-----------------------------------------------------------//

### Error - queue_id too short
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "QUEUE1234"
} 


###
<!-- 
Test Scenario: Server Available Queue ID too short

Expected Outcome:
console: 'Invalid JSON Body'
success response: 
{
  "message": "Input is invalid",
  "status": 400,
  "code": "INVALID_JSON_BODY"
}
-->

//-----------------------------------------------------------//

### Error - queue_id too long
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": "QUEUE123456"
} 


###
<!-- 
Test Scenario: Server Available Queue ID too long

Expected Outcome:
console: 'Invalid JSON Body'
success response: 
{
  "message": "Input is invalid",
  "status": 400,
  "code": "INVALID_JSON_BODY"
}
-->

//-----------------------------------------------------------//

### Error - queue_id not string
PUT http://{{host}}{{path}} HTTP/1.1
Content-Type: application/json

{
    "queue_id": 1234567890
} 


###
<!-- 
Test Scenario: Server Available Queue ID not string

Expected Outcome:
console: 'Invalid JSON Body'
success response: 
{
  "message": "Input is invalid",
  "status": 400,
  "code": "INVALID_JSON_BODY"
}
-->

//-----------------------------------------------------------//